[build]
  publish = "dist"

[[redirects]]
  from = "/sitemap.xml"
  to = "https://tfrebmhionpuowpzedvz.supabase.co/functions/v1/generate-sitemap?file=index"
  status = 200

[[redirects]]
  from = "/sitemap-static.xml"
  to = "https://tfrebmhionpuowpzedvz.supabase.co/functions/v1/generate-sitemap?file=static"
  status = 200

[[redirects]]
  from = "/sitemap-states.xml"
  to = "https://tfrebmhionpuowpzedvz.supabase.co/functions/v1/generate-sitemap?file=states"
  status = 200

[[redirects]]
  from = "/sitemap-districts.xml"
  to = "https://tfrebmhionpuowpzedvz.supabase.co/functions/v1/generate-sitemap?file=districts"
  status = 200

[[redirects]]
  from = "/sitemap-campaigns.xml"
  to = "https://tfrebmhionpuowpzedvz.supabase.co/functions/v1/generate-sitemap?file=campaigns"
  status = 200

[[redirects]]
  from = "/sitemap-schools-*.xml"
  to = "https://tfrebmhionpuowpzedvz.supabase.co/functions/v1/generate-sitemap?file=schools-:splat"
  status = 200
