import { LandingPageBlock } from "./types";

export interface LandingPageLayout {
  id: string;
  name: string;
  description: string;
  preview: string;
  templateType: 'school' | 'district' | 'nonprofit';
  blocks: LandingPageBlock[];
}

export const landingPageLayouts: LandingPageLayout[] = [
  {
    id: "school-modern",
    name: "Modern School",
    description: "Bold hero with stats and campaign showcase",
    preview: "bg-gradient-to-br from-blue-500 to-indigo-600",
    templateType: "school",
    blocks: [
      {
        id: "hero-1",
        type: "hero",
        content: "",
        styles: {
          heroTitle: "Welcome to {{school_name}}",
          heroSubtitle: "Proudly serving {{school_city}}, {{school_state}}",
          heroBackgroundColor: "#1e40af",
          heroHeight: "400px",
          heroOverlayOpacity: "0.5",
          textAlign: "center",
        },
      },
      {
        id: "spacer-1",
        type: "spacer",
        content: "",
        styles: { spacerHeight: "40px" },
      },
      {
        id: "stats-1",
        type: "stats-row",
        content: "",
        styles: {
          stats: [
            { label: "Total Raised", value: "{{total_raised_formatted}}", icon: "dollar" },
            { label: "Active Campaigns", value: "{{active_campaign_count}}", icon: "flag" },
            { label: "Supporters", value: "{{supporter_count}}", icon: "users" },
            { label: "Students", value: "{{school_students}}", icon: "graduation" },
          ],
          backgroundColor: "#f8fafc",
          padding: "40px",
        },
      },
      {
        id: "spacer-2",
        type: "spacer",
        content: "",
        styles: { spacerHeight: "40px" },
      },
      {
        id: "heading-1",
        type: "heading",
        content: "Support Our Programs",
        styles: {
          fontSize: "32px",
          fontWeight: "700",
          textAlign: "center",
          textColor: "#1e293b",
        },
      },
      {
        id: "paragraph-1",
        type: "paragraph",
        content: "Help us provide the best possible education and extracurricular activities for our students. Every contribution makes a difference!",
        styles: {
          fontSize: "18px",
          textAlign: "center",
          textColor: "#64748b",
          padding: "0 20%",
        },
      },
      {
        id: "spacer-3",
        type: "spacer",
        content: "",
        styles: { spacerHeight: "30px" },
      },
      {
        id: "campaigns-1",
        type: "campaign-list",
        content: "",
        styles: {
          campaignListTitle: "Active Campaigns",
          campaignListLimit: 6,
        },
      },
      {
        id: "spacer-4",
        type: "spacer",
        content: "",
        styles: { spacerHeight: "40px" },
      },
      {
        id: "cta-1",
        type: "cta-box",
        content: "",
        styles: {
          ctaTitle: "Ready to Make a Difference?",
          ctaDescription: "Join our community of supporters today and help us achieve our goals.",
          ctaButtonText: "Get Involved",
          ctaButtonUrl: "#campaigns",
          backgroundColor: "#1e40af",
          textColor: "#ffffff",
        },
      },
      {
        id: "spacer-5",
        type: "spacer",
        content: "",
        styles: { spacerHeight: "40px" },
      },
      {
        id: "contact-1",
        type: "contact-info",
        content: "",
        styles: {
          showAddress: true,
          showPhone: true,
          showEmail: true,
          showWebsite: true,
          textAlign: "center",
        },
      },
    ],
  },
  {
    id: "district-overview",
    name: "District Overview",
    description: "Professional layout for school districts",
    preview: "bg-gradient-to-br from-emerald-500 to-teal-600",
    templateType: "district",
    blocks: [
      {
        id: "hero-1",
        type: "hero",
        content: "",
        styles: {
          heroTitle: "{{district_name}}",
          heroSubtitle: "{{district_school_count}} Schools • {{district_total_students}} Students",
          heroBackgroundColor: "#059669",
          heroHeight: "350px",
          textAlign: "center",
        },
      },
      {
        id: "spacer-1",
        type: "spacer",
        content: "",
        styles: { spacerHeight: "40px" },
      },
      {
        id: "heading-1",
        type: "heading",
        content: "Supporting Excellence Across Our District",
        styles: {
          fontSize: "28px",
          fontWeight: "600",
          textAlign: "center",
          textColor: "#1e293b",
        },
      },
      {
        id: "paragraph-1",
        type: "paragraph",
        content: "Our district is committed to providing outstanding educational opportunities. Through community support and fundraising, we enhance programs across all our schools.",
        styles: {
          fontSize: "16px",
          textAlign: "center",
          textColor: "#64748b",
          padding: "0 15%",
        },
      },
      {
        id: "spacer-2",
        type: "spacer",
        content: "",
        styles: { spacerHeight: "40px" },
      },
      {
        id: "stats-1",
        type: "stats-row",
        content: "",
        styles: {
          stats: [
            { label: "Total Raised", value: "{{total_raised_formatted}}", icon: "dollar" },
            { label: "Schools", value: "{{district_school_count}}", icon: "building" },
            { label: "Campaigns", value: "{{campaign_count}}", icon: "flag" },
            { label: "Supporters", value: "{{supporter_count}}", icon: "users" },
          ],
          backgroundColor: "#f0fdf4",
          padding: "40px",
        },
      },
      {
        id: "spacer-3",
        type: "spacer",
        content: "",
        styles: { spacerHeight: "40px" },
      },
      {
        id: "campaigns-1",
        type: "campaign-list",
        content: "",
        styles: {
          campaignListTitle: "District Campaigns",
          campaignListLimit: 9,
        },
      },
    ],
  },
  {
    id: "nonprofit-impact",
    name: "Nonprofit Impact",
    description: "Mission-focused layout with testimonials",
    preview: "bg-gradient-to-br from-purple-500 to-pink-600",
    templateType: "nonprofit",
    blocks: [
      {
        id: "hero-1",
        type: "hero",
        content: "",
        styles: {
          heroTitle: "{{organization_name}}",
          heroSubtitle: "Making a difference in our community",
          heroBackgroundColor: "#7c3aed",
          heroHeight: "400px",
          textAlign: "center",
        },
      },
      {
        id: "spacer-1",
        type: "spacer",
        content: "",
        styles: { spacerHeight: "50px" },
      },
      {
        id: "stats-1",
        type: "stats-row",
        content: "",
        styles: {
          stats: [
            { label: "Funds Raised", value: "{{total_raised_formatted}}", icon: "dollar" },
            { label: "Programs", value: "{{group_count}}", icon: "heart" },
            { label: "Supporters", value: "{{supporter_count}}", icon: "users" },
            { label: "Campaigns", value: "{{campaign_count}}", icon: "flag" },
          ],
          backgroundColor: "#faf5ff",
          padding: "40px",
        },
      },
      {
        id: "spacer-2",
        type: "spacer",
        content: "",
        styles: { spacerHeight: "40px" },
      },
      {
        id: "heading-1",
        type: "heading",
        content: "Our Impact",
        styles: {
          fontSize: "32px",
          fontWeight: "700",
          textAlign: "center",
          textColor: "#1e293b",
        },
      },
      {
        id: "paragraph-1",
        type: "paragraph",
        content: "Every donation helps us continue our mission. Together, we're creating lasting change in our community.",
        styles: {
          fontSize: "18px",
          textAlign: "center",
          textColor: "#64748b",
        },
      },
      {
        id: "spacer-3",
        type: "spacer",
        content: "",
        styles: { spacerHeight: "30px" },
      },
      {
        id: "testimonial-1",
        type: "testimonial",
        content: "",
        styles: {
          testimonialQuote: "This organization has made such a difference in our community. Their dedication and transparency is unmatched.",
          testimonialAuthor: "Community Member",
          testimonialRole: "Supporter since {{current_year}}",
          backgroundColor: "#f8fafc",
        },
      },
      {
        id: "spacer-4",
        type: "spacer",
        content: "",
        styles: { spacerHeight: "40px" },
      },
      {
        id: "campaigns-1",
        type: "campaign-list",
        content: "",
        styles: {
          campaignListTitle: "Support Our Programs",
          campaignListLimit: 6,
        },
      },
      {
        id: "spacer-5",
        type: "spacer",
        content: "",
        styles: { spacerHeight: "40px" },
      },
      {
        id: "cta-1",
        type: "cta-box",
        content: "",
        styles: {
          ctaTitle: "Join Our Mission",
          ctaDescription: "Your support enables us to continue making a positive impact.",
          ctaButtonText: "Donate Today",
          ctaButtonUrl: "#campaigns",
          backgroundColor: "#7c3aed",
          textColor: "#ffffff",
        },
      },
    ],
  },
  {
    id: "school-marketing",
    name: "School Marketing",
    description: "Marketing page to attract schools to sign up for Sponsorly",
    preview: "bg-gradient-to-br from-primary to-primary/80",
    templateType: "school",
    blocks: [
      {
        id: "hero-1",
        type: "hero",
        content: "",
        styles: {
          heroTitle: "Transform Fundraising at {{school_name}}",
          heroSubtitle: "Join hundreds of schools raising more with less effort",
          heroBackgroundColor: "#0f766e",
          heroHeight: "450px",
          heroOverlayOpacity: "0.6",
          textAlign: "center",
        },
      },
      {
        id: "spacer-1",
        type: "spacer",
        content: "",
        styles: { spacerHeight: "60px" },
      },
      {
        id: "pricing-1",
        type: "pricing-highlight",
        content: "",
        styles: {
          pricingTitle: "100% of Donations Go to Your School",
          pricingSubtitle: "Zero platform fees on donations",
          pricingHighlight: "100%",
          pricingDescription: "Unlike traditional platforms that take 5-20%, every dollar donated goes directly to your programs.",
          backgroundColor: "#f0fdf4",
          textColor: "#166534",
        },
      },
      {
        id: "spacer-2",
        type: "spacer",
        content: "",
        styles: { spacerHeight: "60px" },
      },
      {
        id: "heading-1",
        type: "heading",
        content: "Why Schools Choose Sponsorly",
        styles: {
          fontSize: "36px",
          fontWeight: "700",
          textAlign: "center",
          textColor: "#1e293b",
        },
      },
      {
        id: "spacer-3",
        type: "spacer",
        content: "",
        styles: { spacerHeight: "30px" },
      },
      {
        id: "features-1",
        type: "feature-grid",
        content: "",
        styles: {
          features: [
            { icon: "dollar", title: "100% to Your School", description: "No platform fees means more funding for your programs" },
            { icon: "users", title: "Peer-to-Peer Fundraising", description: "Students share personalized links, making fundraising fun and easy" },
            { icon: "file-text", title: "Automatic Tax Receipts", description: "Donors receive IRS-compliant receipts instantly" },
            { icon: "bar-chart", title: "Real-Time Analytics", description: "Track progress and celebrate milestones together" },
          ],
          featureColumns: 2,
          backgroundColor: "#ffffff",
        },
      },
      {
        id: "spacer-4",
        type: "spacer",
        content: "",
        styles: { spacerHeight: "60px" },
      },
      {
        id: "heading-2",
        type: "heading",
        content: "How It Works",
        styles: {
          fontSize: "36px",
          fontWeight: "700",
          textAlign: "center",
          textColor: "#1e293b",
        },
      },
      {
        id: "spacer-5",
        type: "spacer",
        content: "",
        styles: { spacerHeight: "30px" },
      },
      {
        id: "steps-1",
        type: "how-it-works",
        content: "",
        styles: {
          steps: [
            { stepNumber: 1, title: "Create Your Account", description: "Sign up in minutes and set up your school profile" },
            { stepNumber: 2, title: "Launch a Campaign", description: "Choose your fundraising goal and customize your page" },
            { stepNumber: 3, title: "Share & Raise", description: "Students share their personal links with family and friends" },
          ],
          backgroundColor: "#f8fafc",
        },
      },
      {
        id: "spacer-6",
        type: "spacer",
        content: "",
        styles: { spacerHeight: "60px" },
      },
      {
        id: "testimonial-1",
        type: "testimonial",
        content: "",
        styles: {
          testimonialQuote: "Sponsorly made our fundraising so much easier. We raised 40% more than last year and the parents loved how simple it was to donate.",
          testimonialAuthor: "Athletic Director",
          testimonialRole: "High School in Kentucky",
          backgroundColor: "#f8fafc",
        },
      },
      {
        id: "spacer-7",
        type: "spacer",
        content: "",
        styles: { spacerHeight: "60px" },
      },
      {
        id: "cta-1",
        type: "cta-box",
        content: "",
        styles: {
          ctaTitle: "Ready to Transform Your Fundraising?",
          ctaDescription: "Join schools across America who are raising more with Sponsorly",
          ctaButtonText: "Get Started Free",
          ctaButtonUrl: "/signup",
          backgroundColor: "#0f766e",
          textColor: "#ffffff",
        },
      },
      {
        id: "spacer-8",
        type: "spacer",
        content: "",
        styles: { spacerHeight: "40px" },
      },
    ],
  },
  {
    id: "district-marketing",
    name: "District Marketing",
    description: "Marketing page to attract school districts to Sponsorly",
    preview: "bg-gradient-to-br from-blue-600 to-indigo-700",
    templateType: "district",
    blocks: [
      {
        id: "hero-1",
        type: "hero",
        content: "",
        styles: {
          heroTitle: "Empower Every School in {{district_name}}",
          heroSubtitle: "One platform for district-wide fundraising success",
          heroBackgroundColor: "#1e40af",
          heroHeight: "450px",
          textAlign: "center",
        },
      },
      {
        id: "spacer-1",
        type: "spacer",
        content: "",
        styles: { spacerHeight: "60px" },
      },
      {
        id: "heading-1",
        type: "heading",
        content: "District-Wide Benefits",
        styles: {
          fontSize: "36px",
          fontWeight: "700",
          textAlign: "center",
          textColor: "#1e293b",
        },
      },
      {
        id: "spacer-2",
        type: "spacer",
        content: "",
        styles: { spacerHeight: "30px" },
      },
      {
        id: "features-1",
        type: "feature-grid",
        content: "",
        styles: {
          features: [
            { icon: "building", title: "Unified Platform", description: "All {{district_school_count}} schools on one easy-to-manage system" },
            { icon: "shield", title: "Centralized Oversight", description: "District-level reporting and compliance controls" },
            { icon: "dollar", title: "100% to Schools", description: "No platform fees means maximum impact for every school" },
            { icon: "trending-up", title: "Proven Results", description: "Schools using Sponsorly raise 30-50% more on average" },
          ],
          featureColumns: 2,
          backgroundColor: "#ffffff",
        },
      },
      {
        id: "spacer-3",
        type: "spacer",
        content: "",
        styles: { spacerHeight: "60px" },
      },
      {
        id: "pricing-1",
        type: "pricing-highlight",
        content: "",
        styles: {
          pricingTitle: "Zero Platform Fees",
          pricingSubtitle: "More money for what matters",
          pricingHighlight: "$0",
          pricingDescription: "Traditional platforms charge 5-20% in fees. With Sponsorly, 100% of every donation goes directly to your schools.",
          backgroundColor: "#eff6ff",
          textColor: "#1e40af",
        },
      },
      {
        id: "spacer-4",
        type: "spacer",
        content: "",
        styles: { spacerHeight: "60px" },
      },
      {
        id: "steps-1",
        type: "how-it-works",
        content: "",
        styles: {
          steps: [
            { stepNumber: 1, title: "District Setup", description: "We'll help you configure the platform for your district's needs" },
            { stepNumber: 2, title: "School Onboarding", description: "Each school gets their own branded fundraising hub" },
            { stepNumber: 3, title: "Launch & Track", description: "Monitor all campaigns from your district dashboard" },
          ],
          backgroundColor: "#f8fafc",
        },
      },
      {
        id: "spacer-5",
        type: "spacer",
        content: "",
        styles: { spacerHeight: "60px" },
      },
      {
        id: "cta-1",
        type: "cta-box",
        content: "",
        styles: {
          ctaTitle: "Schedule a District Demo",
          ctaDescription: "See how Sponsorly can transform fundraising across your entire district",
          ctaButtonText: "Contact Us",
          ctaButtonUrl: "/contact",
          backgroundColor: "#1e40af",
          textColor: "#ffffff",
        },
      },
    ],
  },
  {
    id: "nonprofit-marketing",
    name: "Nonprofit Marketing",
    description: "Marketing page to attract nonprofits to Sponsorly",
    preview: "bg-gradient-to-br from-purple-600 to-pink-600",
    templateType: "nonprofit",
    blocks: [
      {
        id: "hero-1",
        type: "hero",
        content: "",
        styles: {
          heroTitle: "Fundraise Smarter with {{platform_name}}",
          heroSubtitle: "The modern platform built for mission-driven organizations",
          heroBackgroundColor: "#7c3aed",
          heroHeight: "450px",
          textAlign: "center",
        },
      },
      {
        id: "spacer-1",
        type: "spacer",
        content: "",
        styles: { spacerHeight: "60px" },
      },
      {
        id: "pricing-1",
        type: "pricing-highlight",
        content: "",
        styles: {
          pricingTitle: "Keep Every Dollar You Raise",
          pricingSubtitle: "100% of donations go to your mission",
          pricingHighlight: "100%",
          pricingDescription: "No hidden fees, no platform cuts. Every dollar your donors give goes directly to your programs.",
          backgroundColor: "#faf5ff",
          textColor: "#7c3aed",
        },
      },
      {
        id: "spacer-2",
        type: "spacer",
        content: "",
        styles: { spacerHeight: "60px" },
      },
      {
        id: "features-1",
        type: "feature-grid",
        content: "",
        styles: {
          features: [
            { icon: "file-text", title: "Automatic Tax Receipts", description: "IRS-compliant receipts sent instantly to every donor" },
            { icon: "users", title: "Donor Management", description: "Track relationships, segments, and giving history" },
            { icon: "mail", title: "Built-in Communications", description: "Email campaigns and automated thank-you sequences" },
            { icon: "bar-chart", title: "Impact Analytics", description: "Real-time dashboards to measure your success" },
          ],
          featureColumns: 2,
          backgroundColor: "#ffffff",
        },
      },
      {
        id: "spacer-3",
        type: "spacer",
        content: "",
        styles: { spacerHeight: "60px" },
      },
      {
        id: "steps-1",
        type: "how-it-works",
        content: "",
        styles: {
          steps: [
            { stepNumber: 1, title: "Create Your Profile", description: "Set up your nonprofit and verify your 501(c)(3) status" },
            { stepNumber: 2, title: "Build Your Campaigns", description: "Create beautiful fundraising pages in minutes" },
            { stepNumber: 3, title: "Engage Supporters", description: "Share, track, and grow your donor community" },
          ],
          backgroundColor: "#f8fafc",
        },
      },
      {
        id: "spacer-4",
        type: "spacer",
        content: "",
        styles: { spacerHeight: "60px" },
      },
      {
        id: "cta-1",
        type: "cta-box",
        content: "",
        styles: {
          ctaTitle: "Start Fundraising Today",
          ctaDescription: "Join hundreds of nonprofits already using Sponsorly",
          ctaButtonText: "Get Started Free",
          ctaButtonUrl: "/signup",
          backgroundColor: "#7c3aed",
          textColor: "#ffffff",
        },
      },
    ],
  },
];
